# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["main"]

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Say Hello
        run: echo "Hello from my own Windows machine!"

      - name: Show machine info
        run: |
          echo "Computer name: $env:COMPUTERNAME"
          echo "User: $env:USERNAME"

        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
