name: CI

on:
  push:
    branches: ["main"]

jobs:
  hello:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd

    steps:
      - name: Say Hello
        run: echo "Hello from my own Windows machine!"

      - name: Show machine info
        run: |
          echo Computer name: %COMPUTERNAME%
          echo User: %USERNAME%
